# -*- coding: utf-8 -*-
"""Dumbbell Curl Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9PyqciE_zhlpKdmlDy5VfLNYLChG7j4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import tree

data_kelas_benar = pd.read_csv('/data/gerakan-benar.csv')
data_kelas_salah = pd.read_csv('/data/gerakan-salah.csv')

data_kelas_benar.info()

data_kelas_salah.info()

arr_data_kelas_benar = np.array(data_kelas_benar)
arr_data_kelas_salah = np.array(data_kelas_salah)

arr_data_kelas_benar

arr_data_kelas_salah

df_avg_kelas_benar = pd.DataFrame(data=arr_data_kelas_benar,
                                 columns=['avg_acc1_x','avg_acc1_y','avg_acc1_z',
                                        'avg_giro1_x','avg_giro1_y','avg_giro1_z',
                                        'avg_acc2_x','avg_acc2_y','avg_acc2_z',
                                        'avg_giro2_x','avg_giro2_y','avg_giro2_z',
                                        'avg_acc3_x','avg_acc3_y','avg_acc3_z',
                                        'avg_giro3_x','avg_giro3_y','avg_giro3_z'])

df_avg_kelas_salah = pd.DataFrame(data=arr_data_kelas_salah,
                                 columns=['avg_acc1_x','avg_acc1_y','avg_acc1_z',
                                        'avg_giro1_x','avg_giro1_y','avg_giro1_z',
                                        'avg_acc2_x','avg_acc2_y','avg_acc2_z',
                                        'avg_giro2_x','avg_giro2_y','avg_giro2_z',
                                        'avg_acc3_x','avg_acc3_y','avg_acc3_z',
                                        'avg_giro3_x','avg_giro3_y','avg_giro3_z'])

df_avg_kelas_benar['kelas'] = 'benar'
df_avg_kelas_salah['kelas'] = 'salah'

df_avg_kelas_benar.head()
df_avg_kelas_salah.head()

df_concat = pd.concat([df_avg_kelas_benar[:70], df_avg_kelas_salah[:70]], ignore_index=True)
df_concat

df_concat['kelas'].value_counts()

df_concat['kelas'] = df_concat['kelas'].map({'benar': 1, 'salah': 0})
df_concat

X = np.array(df_concat.iloc[:, :-1])
y = np.array(df_concat.iloc[:, -1])
print(X.shape)
print(y.shape)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Misalnya, data_train adalah data pelatihan, dan label_train adalah label yang sesuai
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

# Inisialisasi model Random Forest
rf_model = RandomForestClassifier(n_estimators=100)

# Latih model
rf_model.fit(X_train, y_train)

# Prediksi
predictions = rf_model.predict(X_test)

# Evaluasi performa
accuracy = accuracy_score(y_test, predictions)
print(f'Accuracy: {accuracy}')

plt.subplots(figsize=(15,10))
tree.plot_tree(rf_model.estimators_[1], filled=True)
plt.show()

from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix, classification_report
cm = confusion_matrix(y_test, predictions)

# Tampilkan confusion matrix dengan ConfusionMatrixDisplay
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['salah','benar'])
disp.plot(cmap='Blues', xticks_rotation='vertical')
plt.title('Confusion Matrix')
plt.show()

print(classification_report(y_test, predictions))

data_uji = pd.DataFrame(X_test)
data_uji

data_uji.to_csv('data_uji.csv')


from micromlgen import port

LABELS = ['SALAH','BENAR'] #our existing labels
classMap = {} #create an empty dict
for i, label in zip(range(2),LABELS): #interate over the range and the labels at the same time
  classMap[i]=label #fill our dict

print(classMap)

c_code = port(rf_model,classmap={0: 'SALAH', 1: 'BENAR'}) #convert our model

#Let's write it into a .h file
modelFile = open("model_RF.h", "w")
modelFile.write(c_code)
modelFile.close()

#Let's print the size of the .h file
import os
model_h_size = os.path.getsize("model_RF.h")
print(f"Header file, model_RF.h, is {model_h_size:,} bytes.")
